# Generated by Django 3.2.8 on 2021-12-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_adveritsment',
            old_name='prize',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='part_of_car_advertisment',
            old_name='prize',
            new_name='price',
        ),
    ]
