# Generated by Django 3.2.9 on 2021-12-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0002_auto_20211204_1457'),
        ('CarAdvertisment', '0003_auto_20211204_1153'),
    ]

    operations = [
    ]
