# Generated by Django 3.2.9 on 2021-12-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0004_merge_0002_auto_20211204_1457_0003_auto_20211204_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_adveritsment',
            name='id_car',
        ),
    ]
