# Generated by Django 3.2.9 on 2021-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0005_remove_car_adveritsment_id_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_adveritsment',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part_of_car_advertisment',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_advertisment',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car_adveritsment',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car_adveritsment',
            name='model',
            field=models.CharField(max_length=30),
        ),
    ]
