# Generated by Django 3.2.9 on 2021-12-05 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarAdvertisment', '0006_auto_20211205_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAdveritsment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('add_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('enabled', 'aktywny'), ('disabled', 'nieaktywny')], max_length=8)),
                ('location', models.CharField(choices=[('ds', 'dolnośląskie'), ('kp', 'kujawsko_pomorskie'), ('lbl', 'lubelskie'), ('lub', 'lubuskie'), ('łód', 'łódzkie'), ('mlp', 'małopolskie'), ('maz', 'mazowieckie'), ('o', 'opolskie'), ('pkrp', 'podkarpackie'), ('pdls', 'podlaskie'), ('pom', 'pomorskie'), ('sl', 'slaśkie'), ('sw', 'świetokrzyskie'), ('wm', 'warmińsko_mazurskie'), ('wlkp', 'wielkopolskie'), ('zp', 'zachodniopomorskie')], max_length=4)),
                ('telephone', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='part_of_car_advertisment',
            new_name='PartOfCarAdvertisment',
        ),
        migrations.RenameModel(
            old_name='service_advertisment',
            new_name='ServiceAdvertisment',
        ),
        migrations.DeleteModel(
            name='car_adveritsment',
        ),
    ]
