# Generated by Django 3.2.9 on 2021-12-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0007_auto_20211205_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caradveritsment',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='partofcaradvertisment',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='serviceadvertisment',
            old_name='id_user',
            new_name='user',
        ),
    ]
