# Generated by Django 3.2.8 on 2021-12-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0008_auto_20211205_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradveritsment',
            name='location',
            field=models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko_pomorskie', 'kujawsko_pomorskie'), ('lubelskie', 'lubelskie'), ('lubelskie', 'lubelskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świetokrzyskie', 'świetokrzyskie'), ('warmińsko_mazurskie', 'warmińsko_mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=19),
        ),
        migrations.AlterField(
            model_name='caradveritsment',
            name='status',
            field=models.CharField(choices=[('aktywne', 'aktywne'), ('nieaktywne', 'nieaktywne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='partofcaradvertisment',
            name='location',
            field=models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko_pomorskie', 'kujawsko_pomorskie'), ('lubelskie', 'lubelskie'), ('lubelskie', 'lubelskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świetokrzyskie', 'świetokrzyskie'), ('warmińsko_mazurskie', 'warmińsko_mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=19),
        ),
        migrations.AlterField(
            model_name='partofcaradvertisment',
            name='status',
            field=models.CharField(choices=[('aktywne', 'aktywne'), ('nieaktywne', 'nieaktywne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceadvertisment',
            name='location',
            field=models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko_pomorskie', 'kujawsko_pomorskie'), ('lubelskie', 'lubelskie'), ('lubelskie', 'lubelskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świetokrzyskie', 'świetokrzyskie'), ('warmińsko_mazurskie', 'warmińsko_mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=19),
        ),
        migrations.AlterField(
            model_name='serviceadvertisment',
            name='service',
            field=models.CharField(choices=[('lakierowanie', 'lakierowanie'), ('blacharstwo', 'blacharstwo'), ('mechanika', 'mechanika')], max_length=12),
        ),
        migrations.AlterField(
            model_name='serviceadvertisment',
            name='status',
            field=models.CharField(choices=[('aktywne', 'aktywne'), ('nieaktywne', 'nieaktywne')], max_length=10),
        ),
    ]
