# Generated by Django 4.0 on 2021-12-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0011_remove_partofcaradvertisment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caradveritsment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='partofcaradvertisment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceadvertisment',
            name='user',
        ),
    ]
