# Generated by Django 3.2.8 on 2021-12-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAdvertisment', '0014_alter_serviceadvertisment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradveritsment',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='partofcaradvertisment',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceadvertisment',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
