# Generated by Django 3.2.9 on 2021-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_adveritsment',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='car_adveritsment',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30),
        ),
    ]
