# Generated by Django 3.2.8 on 2021-12-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='part_of_car_advertisment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('add_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prize', models.IntegerField()),
                ('status', models.CharField(choices=[('enabled', 'aktywny'), ('disabled', 'nieaktywny')], max_length=8)),
                ('location', models.CharField(choices=[('ds', 'dolnośląskie'), ('kp', 'kujawsko_pomorskie'), ('lbl', 'lubelskie'), ('lub', 'lubuskie'), ('łód', 'łódzkie'), ('mlp', 'małopolskie'), ('maz', 'mazowieckie'), ('o', 'opolskie'), ('pkrp', 'podkarpackie'), ('pdls', 'podlaskie'), ('pom', 'pomorskie'), ('sl', 'slaśkie'), ('sw', 'świetokrzyskie'), ('wm', 'warmińsko_mazurskie'), ('wlkp', 'wielkopolskie'), ('zp', 'zachodniopomorskie')], max_length=4)),
                ('telephone', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='service_avertisment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('service', models.CharField(choices=[('spraying', 'lakierowanie'), ('tinywork', 'blacharstwo'), ('car_mechanic', 'mechanika')], max_length=12)),
                ('add_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('enabled', 'aktywny'), ('disabled', 'nieaktywny')], max_length=8)),
                ('location', models.CharField(choices=[('ds', 'dolnośląskie'), ('kp', 'kujawsko_pomorskie'), ('lbl', 'lubelskie'), ('lub', 'lubuskie'), ('łód', 'łódzkie'), ('mlp', 'małopolskie'), ('maz', 'mazowieckie'), ('o', 'opolskie'), ('pkrp', 'podkarpackie'), ('pdls', 'podlaskie'), ('pom', 'pomorskie'), ('sl', 'slaśkie'), ('sw', 'świetokrzyskie'), ('wm', 'warmińsko_mazurskie'), ('wlkp', 'wielkopolskie'), ('zp', 'zachodniopomorskie')], max_length=4)),
                ('telephone', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='car_adveritsment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('add_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prize', models.IntegerField()),
                ('status', models.CharField(choices=[('enabled', 'aktywny'), ('disabled', 'nieaktywny')], max_length=8)),
                ('location', models.CharField(choices=[('ds', 'dolnośląskie'), ('kp', 'kujawsko_pomorskie'), ('lbl', 'lubelskie'), ('lub', 'lubuskie'), ('łód', 'łódzkie'), ('mlp', 'małopolskie'), ('maz', 'mazowieckie'), ('o', 'opolskie'), ('pkrp', 'podkarpackie'), ('pdls', 'podlaskie'), ('pom', 'pomorskie'), ('sl', 'slaśkie'), ('sw', 'świetokrzyskie'), ('wm', 'warmińsko_mazurskie'), ('wlkp', 'wielkopolskie'), ('zp', 'zachodniopomorskie')], max_length=4)),
                ('telephone', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassicGarage.car')),
            ],
        ),
    ]
