# Generated by Django 3.2.8 on 2021-12-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassicGarage', '0003_auto_20211203_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_adveritsment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
